
# parsetab.py
# This file is automatically generated. Do not edit.
_tabversion = '3.8'

_lr_method = 'LALR'

_lr_signature = 'A8301231E07080D2BD9866FF346495DF'
    
_lr_action_items = {'CLASSIFIER':([0,],[2,]),'$end':([1,2,],[0,-1,]),}

_lr_action = {}
for _k, _v in _lr_action_items.items():
   for _x,_y in zip(_v[0],_v[1]):
      if not _x in _lr_action:  _lr_action[_x] = {}
      _lr_action[_x][_k] = _y
del _lr_action_items

_lr_goto_items = {'method':([0,],[1,]),}

_lr_goto = {}
for _k, _v in _lr_goto_items.items():
   for _x, _y in zip(_v[0], _v[1]):
       if not _x in _lr_goto: _lr_goto[_x] = {}
       _lr_goto[_x][_k] = _y
del _lr_goto_items
_lr_productions = [
  ("S' -> method","S'",1,None,None,None),
  ('method -> CLASSIFIER','method',1,'p_method','grammar.py',7),
  ('clasification -> CLASSIFIER_METHOD','clasification',1,'p_clasification','grammar.py',21),
  ('crossValidation -> CROSSVALIDATION_VAR = bool','crossValidation',3,'p_crossValidation','grammar.py',37),
  ('crossValidation -> CROSSVALIDATION_VAR = kfold','crossValidation',3,'p_crossValidation','grammar.py',38),
  ('kfold -> ( num , num )','kfold',5,'p_kfold','grammar.py',42),
  ('uploadFile -> UPLOAD_COMMAND ( upload )','uploadFile',4,'p_uploadFile','grammar.py',46),
  ('upload -> PATH','upload',1,'p_upload','grammar.py',59),
  ('csv -> CSV_VAR = bool','csv',3,'p_csv','grammar.py',63),
  ('csv -> CSV_VAR = ( num , num )','csv',7,'p_csv','grammar.py',64),
  ('csv -> CSV_VAR = ( num )','csv',5,'p_csv','grammar.py',65),
  ('csv -> CSV_VAR ( upload )','csv',4,'p_csv','grammar.py',66),
  ('num -> INT','num',1,'p_num','grammar.py',69),
  ('bool -> BOOLEAN','bool',1,'p_bool','grammar.py',73),
  ('printResults -> PRINT','printResults',1,'p_printResults','grammar.py',77),
]
